kardexApp/urls.py
from django.contrib import admin
from django.urls import path
from kardex.views import PortadaView

urlpatterns = [
    path('', PortadaView.as_view(), name='portada'),
    path('admin/', admin.site.urls),
]

kardex/models.py
from datetime import timedelta

from django.db import models

TIPO_MATERIA = (
    ('1', 'Obligatoria'),
    ('2', 'Optativa')
)
INICIO: int = 15


class Materia(models.Model):
    clave = models.CharField(max_length=4)
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=1, choices=TIPO_MATERIA)
    semestre = models.PositiveSmallIntegerField()
    puntos = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name = "Materia"
        verbose_name_plural = "Materias"

    def __str__(self) -> str:
        return f'{self.clave} {self.nombre}'


class Clase(models.Model):
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, related_name='materia_clase')
    periodo = models.CharField(max_length=6)
    grupo = models.CharField(max_length=4)
    asesor = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Clase'
        verbose_name_plural = 'Clases'

    def __str__(self) -> str:
        return f'{self.materia.clave} - {self.grupo} - {self.materia.nombre} ({self.periodo})'


class Tarea(models.Model):
    clase = models.ForeignKey(Clase, on_delete=models.CASCADE, related_name='clase_tarea')
    unidad = models.PositiveSmallIntegerField()
    actividad = models.CharField(max_length=2)
    f_inicio = models.DateField(editable=False)
    f_entrega = models.DateField()
    desc = models.TextField()

    class Meta:
        verbose_name = 'Tarea'
        verbose_name_plural = 'Tareas'

    def __str__(self) -> str:
        if self.actividad.isnumeric():
            return f'{self.clase.materia.clave}:{self.unidad:02d}:{int(self.actividad):02d}'
        else:
            return f'{self.clase.materia.clave}:{self.unidad:02d}:{self.actividad}'

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.f_inicio = self.f_entrega - timedelta(days=INICIO)
        super(Tarea, self).save(force_insert, force_update)

kardex/views.py
from django.views.generic import ListView

from .models import Materia


class PortadaView(ListView):
    queryset = Materia.objects.all().order_by('semestre', 'clave')
    template_name = "kardex/index.html"

kardex/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"></script>

    <title>Kardex App</title>
  </head>
    <body>
      <main>
        <div class="container py-4">
        <header class="pb-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
             <img src="https://upload.wikimedia.org/wikipedia/commons/c/ca/Escudo-UNAM-escalable.svg" alt="UNAM" width="40" height="40">
              <span class="fs-4">Kardex App</span>
          </a>
        </header>

        <div class="p-5 mb-4 bg-light rounded-3">
          <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Control de Calificaciones</h1>
            <p class="col-md-8 fs-4">
                lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto at atque commodi cumque eum hic itaque necessitatibus officia quae quibusdam reiciendis, soluta voluptas? Aperiam fugiat incidunt labore obcaecati provident! Repellendus.
            </p>
            <button class="btn btn-primary btn-lg" type="button">Example button</button>
          </div>
        </div>

        <div class="row align-items-md-stretch">
          <div class="col-md-12">
            <div class="h-100 p-5 bg-light border rounded-3">
              <h2>Kardex</h2>
                <div class="row">
                    <div class="col">
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
          </div>
        </div>

        <footer class="pt-3 mt-4 text-muted border-top">
          &copy; 2022
        </footer>
      </div>
    </main>

</body>
</html>

kardex/templates/kardex/index.html
{% extends "base.html" %}

{% block content %}
    {% regroup materia_list by semestre as semestres %}
    <pre>{{ semestre_list }}</pre>
    <div class="accordion" id="semestre">
        {% for semestre in semestres %}
            <div class="accordion-item">
                <h2 class="accordion-header" id="semestre{{ semestre.grouper }}">
                    <button class="accordion-button" data-bs-toggle="collapse"
                            data-bs-target="#collapse{{ semestre.grouper }}"
                            aria-expanded="true" aria-controls="collapse{{ semestre.grouper }}">
                        Semestre {{ semestre.grouper }}
                    </button>
                </h2>

                <div class="accordion-collapse collapse {% if forloop.first %}show{% endif %}"
                     id="collapse{{ semestre.grouper }}"
                     aria-labelledby="materia{{ semestre.grouper }}" data-bs-parent="#semestre">
                    <div class="accordion-body">
<table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Clave</th>
                                <th>Nombre</th>
                                <th>Créditos</th>
                                <th>Calificación</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for materia in semestre.list %}
                                <tr>
                                    <td>{{ materia.clave }}</td>
                                    <td>{{ materia.nombre }}</td>
                                    <td>{{ materia.creditos }}</td>
                                    <td>{{ materia.calif }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}